## **Módulo Matéria 04** - Análise de Regressão em Python part 04

## Prática no Colab

### 321 Material de Apoio - Scikit

### 322 Prática no Colab I
<h1>Tema central: Modelagem de regressão para estimar preços de casas em Boston</h1><h2>Técnicas de modelagem selecionadas</h2><ul><li>Regressão linear do sklearn</li><li>Support vector regression (SVR) do sklearn</li><li>Decision tree regression do XGBoost</li></ul><h2>Premissas dos modelos</h2><ul><li>Apenas variáveis numéricas</li></ul><h2>Design do teste</h2><ul><li>Separação do dataset:<ul><li>20% para teste (x_test e y_test)</li><li>80% para treino (x_train e y_train)</li><li>Utilizando train_test_split do sklearn</li></ul></li></ul><h2>Regressão Linear</h2><ul><li>Importada do sklearn</li><li>Modelo definido chamando a função LinearRegression()</li><li>Modelo treinado com .fit(X_train, y_train)</li></ul><h2>Próximos passos</h2><ul><li>Treinar os outros modelos (SVR e XGBoost)</li><li>Testar os modelos</li><li>Otimizar hiperparâmetros</li><li>Comparar desempenho dos modelos</li></ul>

In [ ]:
pip install scikit-learn

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
fetch_california_housing()

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [ ]:
california_housing = fetch_california_housing()

In [ ]:
X = california_housing.data #CARACTERISTICAS DAS CASAS
y = california_housing.target #PREÇO CONHECIDO DAS CASAS - TARGET

In [ ]:
print(X)

[[   8.3252       41.            6.98412698 ...    2.55555556
    37.88       -122.23      ]
 [   8.3014       21.            6.23813708 ...    2.10984183
    37.86       -122.22      ]
 [   7.2574       52.            8.28813559 ...    2.80225989
    37.85       -122.24      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]


In [ ]:
print(y)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


## Modeling Techniques
1. Regressão Linear do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html>
2. Support Vector Regression do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html>
3. Decision Tree Regression do XGBoost
<https://xgboost.readthedocs.io/en/stable/python/python_api.html>

## Modeling Assumptions:
Apenas variáveis numéricas

## Test Design

### Dataset split:
Separação de Train/TEst dataset padrão com 20% de massa para teste via método SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html>

## Métrica de avaliação do modelo
R2, R2 ajustado, MSE, RMSE e MAE
Escolher entre MSE e MAE
MSE  Média dos quadrados dos erros - Penalizar se modelo erra muito
MAE  Média do erro absoluto - tratando todos erros iguais
RMSE Raiz quadrada
Validação da métrica MSE E RMSE para penalizar grandes erros de previsão.
Utilizando o método do SKLEARN
<https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html>

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVR
import pandas as pd
import numpy as np
from xgboost import XGBRegressor

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train)

[[   3.2596       33.            5.0176565  ...    3.6918138
    32.71       -117.03      ]
 [   3.8125       49.            4.47354497 ...    1.73809524
    33.77       -118.16      ]
 [   4.1563        4.            5.64583333 ...    2.72321429
    34.66       -120.48      ]
 ...
 [   2.9344       36.            3.98671727 ...    3.33206831
    34.03       -118.38      ]
 [   5.7192       15.            6.39534884 ...    3.17889088
    37.58       -121.96      ]
 [   2.5755       52.            3.40257649 ...    2.10869565
    37.77       -122.42      ]]


In [ ]:
print(y_train)

[1.03  3.821 1.726 ... 2.221 2.835 3.25 ]


## Técnica 1. Regressão Linear

In [ ]:
regLinear = LinearRegression()

In [ ]:
Treinado = regLinear.fit(X_train, y_train)

### 323 Prática no Colab II
<h1>Tema central:</h1><p>Construção e avaliação de modelos de machine learning para prever o preço de imóveis</p><h2>Tópicos abordados:</h2><ul><li>Seleção de modelos<ul><li>Requisitos técnicos<ul><li>Regressão Linear</li><li>Support Vector Regression (SVR)</li><li>XGBoost Regressor</li></ul></li></ul></li><li>Geração de teste<ul><li>Separação do dataset<ul><li>Treino</li><li>Teste</li></ul></li><li>Métricas de avaliação<ul><li>Mean Squared Error (MSE)</li><li>Root Mean Squared Error (RMSE)</li></ul></li></ul></li><li>Construção dos modelos (Modeling)<ul><li>Regressão Linear</li><li>Support Vector Regression</li><li>XGBoost Regressor</li></ul></li><li>Avaliação dos modelos<ul><li>Predições no conjunto de teste</li><li>Cálculo das métricas MSE e RMSE</li><li>Comparação dos erros</li><li>Escolha do melhor modelo (menor RMSE)</li></ul></li><li>Próximos passos<ul><li>Otimização de hiperparâmetros</li><li>Melhoria dos modelos</li></ul></li></ul><p>O vídeo mostra o processo de construção, avaliação e comparação de três modelos de regressão para prever o preço de imóveis, utilizando conjuntos de treino e teste separados do dataset. As métricas MSE e RMSE são calculadas entre os valores previstos e reais no conjunto de teste para escolher o melhor modelo, que foi o XGBoost Regressor. O próximo passo será a otimização dos hiperparâmetros para tentar melhorar ainda mais o desempenho do modelo selecionado.</p>

In [ ]:
yLinear = regLinear.predict(X_test)

In [ ]:
print(yLinear)

[0.71912284 1.76401657 2.70965883 ... 4.46877017 1.18751119 2.00940251]


In [ ]:
y_test

array([0.477  , 0.458  , 5.00001, ..., 5.00001, 0.723  , 1.515  ])

In [ ]:
MSELinear = mean_squared_error(y_test, yLinear)

In [ ]:
print("MSE:", MSELinear)
print("RMSE:", np.sqrt(MSELinear))

MSE: 0.5558915986952422
RMSE: 0.7455813830127749


## Técnica SVR

In [ ]:
regSVR = SVR().fit(X_train, y_train)

In [ ]:
ySVR = regSVR.predict(X_test)

In [ ]:
print(ySVR)

[1.74839687 1.77561334 1.88771095 ... 1.81632304 1.82315874 1.73570366]


In [ ]:
MSESVR = mean_squared_error(y_test, ySVR)

In [ ]:
print("MSE:", MSESVR)
print("RMSE:", np.sqrt(MSESVR))

MSE: 1.3320115421348744
RMSE: 1.1541280440812771


In [ ]:
## Técnica 3. Decision Tree Regression (XGBoost)

In [ ]:
regXGB = XGBRegressor().fit(X_train, y_train)

In [ ]:
yXGB = regXGB.predict(X_test)

In [ ]:
MSEXGB = mean_squared_error(y_test, yXGB)

In [ ]:
print("MSE XGB:", MSEXGB)
print("RMSE XGB:", np.sqrt(MSEXGB))

MSE XGB: 0.2225899267544737
RMSE XGB: 0.4717943691423984


### 324 Prática no Colab III
<h1>Tema central</h1><p>Otimização de modelos de machine learning para previsão de preços de imóveis</p><h2>Tópicos abordados</h2><ul><li><p>Escolha de modelos</p><ul><li>Regressão Linear (Scikit-Learn)</li><li>Support Vector Regression (Scikit-Learn)</li><li>Decision Tree Regression (XGBoost)</li></ul></li><li><p>Avaliação de modelos</p><ul><li>Métricas: Mean Squared Error (MSE), Root Mean Squared Error (RMSE)</li><li>Decision Tree Regression (XGBoost) teve melhor desempenho</li></ul></li><li><p>Otimização de hiperparâmetros</p><ul><li>Utilizou Grid Search CV (Scikit-Learn)</li><li>Definiu parâmetros e valores a serem testados</li><li>Encontrou melhor combinação de hiperparâmetros</li><li>Reduziu MSE e RMSE</li></ul></li><li><p>Processo</p><ul><li>Split de dados em treino e teste</li><li>Execução dos modelos com parâmetros default</li><li>Comparação do desempenho dos modelos</li><li>Otimização do melhor modelo (XGBoost)</li><li>Avaliação do modelo otimizado</li></ul></li><li><p>Conclusão</p><ul><li>Otimização dos hiperparâmetros melhorou o desempenho do modelo</li><li>XGBoost com hiperparâmetros otimizados teve o melhor resultado</li></ul></li></ul><p>Espero que esse resumo em forma de mapa mental ajude a ter uma visão geral dos principais tópicos e processo abordados no vídeo. Caso tenha alguma dúvida ou precise de mais detalhes em algum ponto, fique à vontade para perguntar.</p>

In [ ]:
regXGB.get_params().keys()

dict_keys(['objective', 'base_score', 'booster', 'callbacks', 'colsample_bylevel', 'colsample_bynode', 'colsample_bytree', 'device', 'early_stopping_rounds', 'enable_categorical', 'eval_metric', 'feature_types', 'gamma', 'grow_policy', 'importance_type', 'interaction_constraints', 'learning_rate', 'max_bin', 'max_cat_threshold', 'max_cat_to_onehot', 'max_delta_step', 'max_depth', 'max_leaves', 'min_child_weight', 'missing', 'monotone_constraints', 'multi_strategy', 'n_estimators', 'n_jobs', 'num_parallel_tree', 'random_state', 'reg_alpha', 'reg_lambda', 'sampling_method', 'scale_pos_weight', 'subsample', 'tree_method', 'validate_parameters', 'verbosity'])

In [ ]:
# max_depth profundidade máxima
# learning_rate velocidade de aprendizagem da arvore
# objective
# booster tipo específico
# n_jobs processamento em paralelo
# gamma criação de uma folha na arvore de decisão
# min_child_weight peso do nó filho da arvore
# delta
# porcentagem a razão amostra e subamostras
parameters = {
    "max_depth": [1],
    "learning_rate": [0.1,0.2,0.3],
    "objective": ['reg:squarederror'],
    "booster": ['gbtree'],
    "n jobs": [5],
    "gamma": [0,1],
    "min_child_weight": [1,3],
    "max_delta_step": [0,1],
    "subsample": [0.5,1]
}

In [ ]:
# refit qual é metrica melhor para meu modelo
# verbose sua função vai descrevendo passo a passo
xgbGrid =GridSearchCV(XGBRegressor(), parameters, refit = 'neg_mean_squared_error', verbose= True)

In [ ]:
xgbGridModel = xgbGrid.fit(X_train, y_train)

In [ ]:
xgbGridModel.best_params_

In [ ]:
yGrid = xgbGridModel.predict(X_test)

In [ ]:
print('MSE XGB Grid:', MSEGrid)
print('RMSE XGB Grid:', np.sqrt(MSEGrid))